# -*- coding: utf-8 -*-
"""Parametric_PDF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12WkC5S7HRKbQVsA2tzh_ueKk0Vmz3xwS
"""

import matplotlib.pyplot as plt

import numpy as np
from numpy.random import normal

sample=normal(loc=50,scale=5,size=1000)

plt.hist(sample)

#look like noremal
mean=sample.mean()
std=sample.std()

#now fitt for normal dist
from scipy.stats import norm
dist= norm(mean,std)

# from certain range we are choosing point
val=np.linspace(sample.min(),sample.max(),100)

probabilities = [dist.pdf(value) for value in val]

plt.hist(sample,density=True)
plt.plot(val,probabilities)